Add guideline link
niwaniwa/misskey pull request #144
Opened 2024-02-17 10:59 UTC by Sayamame-beans

## What

Close: #137 

## Why

## Additional info (optional)

動作は確認しましたが、やり方が正しいかは分かりません

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-02-17 11:02 UTC, anatawa12 requested changes

2024-02-17 11:02 UTC, anatawa12 commented on packages/frontend/src/components/MkVisitorDashboard.vue
> +	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
deviderは常にあるべきだとと思います。上部のセクションがあるときにdividerが追加されるという形なので

2024-02-17 11:02 UTC, anatawa12 commented on packages/frontend/src/ui/_common_/common.ts
> +	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
同じく

2024-02-17 11:06 UTC, Sayamame-beans commented on packages/frontend/src/components/MkVisitorDashboard.vue
> +	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
…? dividerの存在条件は変えていません

2024-02-17 11:07 UTC, Sayamame-beans commented on packages/frontend/src/components/MkVisitorDashboard.vue
> +	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
ああ、そういう

2024-02-17 11:09 UTC, Sayamame-beans commented on packages/frontend/src/components/MkVisitorDashboard.vue
> +	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
```suggestion
	}, { type: 'divider' }, {
```

2024-02-17 11:09 UTC, Sayamame-beans commented on packages/frontend/src/ui/_common_/common.ts
> +	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
```suggestion
	}, (!instance.impressumUrl && !instance.tosUrl && !instance.privacyPolicyUrl) ? undefined : { type: 'divider' }, {
```
```suggestion
	}, { type: 'divider' }, {
```

2024-02-17 11:10 UTC, anatawa12 approved these changes
CI通ったらよし！

2024-02-17 11:11 UTC, anatawa12 commented
(CIはコンフリクトあると通らないです)

2024-02-17 11:20 UTC, merged

2024-05-01 14:18 UTC, Sayamame-beans commented
おあ～
ハードコードにしてた…

気が向いたら書き換えます(参照する先が変わった)