spec(backend/NoteCreateService): ローカルユーザーがまだ誰もフォローしていないリモートユーザーによる通知を…
niwaniwa/misskey pull request #149
Opened 2024-02-19 18:08 UTC by anatawa12

…引き起こす可能性のある投稿を拒否できるように (MisskeyIO#462)

Cherry-picked from 738b4d69701a9d4b232f6a44b340782d096b182b, 1b3adcc2bbc695a0f28f5865a6705e0e59830962, 33cb50761ec12fc0df0e6f99ba97e0d5d4e580fc, a27af00e23a5283e357de1e6bf2a47ebefaa77c2, 5c6236bb0f1fde9140e331c9e1390bb5fccd4f9a

## What

Fixes #146

## Why

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-02-19 18:09 UTC, anatawa12 commented
これ有効無効envでいいの？という気持ちが少し

2024-02-19 18:11 UTC, Sayamame-beans commented
> これ有効無効envでいいの？という気持ちが少し

同じ気持ちです

2024-02-19 18:20 UTC, anatawa12 commented
configにする？

2024-02-19 18:28 UTC, anatawa12 commented
した

2024-02-19 18:28 UTC, Sayamame-beans commented
とりあえずこれをそのまま採用するという前提に立てば、configかサーバー側の設定項目雑に生やすかのどちらかかなぁ(実質前者のみ?)という感じでしょうか

2024-02-19 18:30 UTC, anatawa12 commented
metaに追加は面倒なのでconfigにしました。

2024-02-19 18:34 UTC, anatawa12 commented
(changelogのコンフリクト面倒なのでできればマージしたいのでreview急いでほしい)

2024-02-19 18:35 UTC, Sayamame-beans commented
む…
じゃあ見ます

2024-02-19 18:56 UTC, Sayamame-beans requested changes

2024-02-19 18:56 UTC, Sayamame-beans commented on CHANGELOG.md
> +- ローカルユーザーがまだ誰もフォローしていないリモートユーザーによる通知を引き起こす可能性のある投稿を拒否できるように
```suggestion
- ローカルユーザーがまだ誰もフォローしていないリモートユーザーによる、通知を引き起こす可能性のある投稿を拒否できるように
```

2024-02-19 18:57 UTC, Sayamame-beans commented
else Approve

2024-02-19 18:57 UTC, merged

2024-02-21 04:26 UTC, Sayamame-beans commented
additional patchがあるっぽい
https://github.com/MisskeyIO/misskey/pull/466