virtual kemomimi relay timeline
niwaniwa/misskey pull request #174
Opened 2024-04-11 10:03 UTC by anatawa12

## What

Fixes #57

## Why

- めっちゃ需要がある。
- GTLが速すぎる

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-04-11 11:14 UTC, anatawa12 commented
別サーバーにも投げるつもりなので、update branchはいろいろ仕様を直してからやります。

2024-04-11 11:26 UTC, Sayamame-beans requested changes

2024-04-11 11:26 UTC, Sayamame-beans commented on locales/ja-JP.yml
> +  vmimiRelay: "Virtual Kemomimi リレー"
```suggestion
  vmimiRelay: "ぶいみみリレー"
```

2024-04-11 11:28 UTC, anatawa12 commented on locales/ja-JP.yml
> +  vmimiRelay: "Virtual Kemomimi リレー"
参考: https://misskey.niri.la/notes/9ryptwyxx1

ぶいみみ派多そうね

2024-04-11 12:09 UTC, Sayamame-beans commented on packages/backend/src/core/VmimiRelayTimelineService.ts
> +		const instanceList = await this.httpRequestService.getJson<VmimiInstanceList>('https://relay.virtualkemomimi.net/api/servers');
リレーサーバーが一時的に停止していたりして取得に失敗したらどうなるんでしょう…? 1日後まで壊れたままになります? 古い情報のまま次に取得成功するまで維持されます?

2024-04-11 12:09 UTC, Sayamame-beans commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
"TLに他の人への返信を含める"オプションは実装困難?

2024-04-11 12:11 UTC, anatawa12 commented on packages/backend/src/core/VmimiRelayTimelineService.ts
> +		const instanceList = await this.httpRequestService.getJson<VmimiInstanceList>('https://relay.virtualkemomimi.net/api/servers');
最初の取得失敗したときは想定忘れてました

２回目以降は前回の取得が使われるはず

初回を想定した処理等作っておきます

2024-04-11 12:46 UTC, anatawa12 commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
他人への返信を除外するということです？

2024-04-11 12:47 UTC, anatawa12 commented on packages/backend/src/core/VmimiRelayTimelineService.ts
> +		const instanceList = await this.httpRequestService.getJson<VmimiInstanceList>('https://relay.virtualkemomimi.net/api/servers');
5f79f2dc78e9610f0a7bf7df2db6a19592e9c9fa で実装した

2024-04-11 12:49 UTC, Sayamame-beans commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
自身がフォローしていないユーザーAが自身がフォローしていないユーザーBに返信している場合もTLに載せるオプションの話です(LTL/STLにはあります)

2024-04-11 12:50 UTC, anatawa12 commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
GTLからリレーのみを抜き取ってくる形なので多分すでにリプライ含まれてます

2024-04-11 12:50 UTC, Sayamame-beans commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
なるほど? GTLってそうなんですね…

2024-04-11 12:51 UTC, anatawa12 commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
逆にリレー外へのリプライを除外は作ってもいいかもしれない。

2024-04-11 12:53 UTC, Sayamame-beans commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
確かに…

2024-04-11 12:53 UTC, anatawa12 commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
どうします？

2024-04-11 13:06 UTC, anatawa12 commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
参考: https://misskey.niri.la/notes/9ryt39uwsi

2024-04-11 13:07 UTC, Sayamame-beans commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
個人的にはあっても良さそう～って思ってますが(リレーTLの趣旨的に…?)、一応反応待ちます

2024-04-11 14:30 UTC, anatawa12 commented on packages/backend/src/server/api/endpoints/notes/vmimi-relay-timeline.ts
> +/*
実装すること自体のコストは低かったので追加しちゃいました

2024-04-11 18:21 UTC, anatawa12 commented
CIエラーはCI側の問題だったわ

2024-04-11 22:09 UTC, Sayamame-beans commented on packages/backend/src/server/api/stream/channels/vmimi-relay-timeline.ts
> +		// 関係ない返信は除外
大体良さそうな雰囲気を感じるんですが、ここのブロック(57-62)にちょっと不安を感じるので、excludeReplies(厳密にはexcludeRepliesToNoRelay的な感じだと思うけど)との兼ね合いも含めて条件問題ないか念の為見て欲しいです

2024-04-12 09:04 UTC, anatawa12 commented on packages/backend/src/server/api/stream/channels/vmimi-relay-timeline.ts
> +		// 関係ない返信は除外
コピペの部分だけどこれいらなそうだね。消します

2024-04-12 09:08 UTC, anatawa12 commented on packages/backend/src/server/api/stream/channels/vmimi-relay-timeline.ts
> +		// 関係ない返信は除外
613a6f878de1493947953a1b1172b44c324a8ec0

2024-04-12 10:15 UTC, Sayamame-beans commented on packages/backend/src/server/api/stream/channels/vmimi-relay-timeline.ts
> +		if (note.renote && !note.text && isUserRelated(note, this.userIdsWhoMeMutingRenotes)) return;
これ多分コピペだと思うんですけど、手前のリノート判定に比べて、ファイルの有無が無くて引用判定のチェックが甘い…?

2024-04-12 10:16 UTC, anatawa12 commented on packages/backend/src/server/api/stream/channels/vmimi-relay-timeline.ts
> +		if (note.renote && !note.text && isUserRelated(note, this.userIdsWhoMeMutingRenotes)) return;
たしかに。

ここら、utilsにまとめるリファクタ本家で後でやるつもりがあるので取り敢えず今はこのままにします。

2024-04-12 10:19 UTC, Sayamame-beans commented on packages/backend/src/server/api/stream/channels/vmimi-relay-timeline.ts
> +		if (note.renote && !note.text && isUserRelated(note, this.userIdsWhoMeMutingRenotes)) return;
OK!

2024-04-12 10:19 UTC, Sayamame-beans approved these changes
might be ok!

2024-04-12 10:33 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - ぶいみみリレータイムラインは、[Virtual Kemomimiリレー]に参加したサーバーのノートのみが流れるタイムラインです
```suggestion
  - ぶいみみリレータイムラインは、[Virtual Kemomimiリレー]に参加しているサーバーからのノートのみが流れるタイムラインです
```

2024-04-12 11:11 UTC, merged

2024-04-16 08:57 UTC, anatawa12 commented
Note: reimplemented and social is added in #176