feat: 画像縮小・非可逆圧縮の設定を分離
niwaniwa/misskey pull request #179
Opened 2024-04-20 14:04 UTC by i544c-me

## What
cherry-picked from https://github.com/i544c-me/buicha-social-misskey/pull/3
この PR では、4択となっていた画像圧縮の設定を2つのトグルに分け、ユーザーがより直感的に設定できるよう修正を行いました。

Before
![スクリーンショット 2024-04-20 223655](https://github.com/i544c-me/buicha-social-misskey/assets/131976645/3c0581f0-239b-4f1b-b228-d0064afa5be0)

After
![スクリーンショット 2024-04-20 222914](https://github.com/i544c-me/buicha-social-misskey/assets/131976645/a37bb89b-385e-4359-8d60-d5f18ccda352)

## Why
縮小の有無と非可逆圧縮の有無は分けて考えられますが、これを4択で提示してしまうとユーザーが混乱するのではないかと考えました。
2つのトグルならそれぞれ別に考えられますし、説明文も明確で分かりやすくなるかと思います。

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-04-20 14:09 UTC, Sayamame-beans commented
ありがとうございます！

to anatawa12
- [ ] 既存の設定が失われるので互換性のある形式にするかMigrationする

2024-04-20 14:23 UTC, anatawa12 requested changes
ありがとうございます。

2024-04-20 14:23 UTC, anatawa12 commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = computed(defaultStore.makeGetterSetter('imageCompressionLossy'));
更新によって設定が保持されないと問題になるので、`imageResize` `imageCompressionLossy`は`ref()`で処理し、`imageCompressionMode`は`imageResize`と`imageCompressionLossy`を`watch`して`imageCompressionMode`に保存する形にしていただきたいです。

以下コードイメージで動作確認していません

```ts
const imageCompressionMode = computed(defaultStore.makeGetterSetter('imageCompressionMode'));
const imageResize = ref(imageCompressionMode.value.startsWith('resize'));
const imageCompressionLossy = ref(imageCompressionMode.value.endsWith('CompressLossy'));

watch([imageResize, imageCompressionLossy], ([imageResizeValue, imageCompressionLossyValue]) => {
    const resizeMode: 'resize' | 'noResize' = imageResizeValue ? 'resize' : 'noResize';
    const compressionMode: 'Compress' | 'CompressLossy' = imageCompressionLossyValue ? 'CompressLossy' : 'Compress';
    imageCompressionMode.value = resizeMode + compressionMode;
})

```

2024-04-20 14:40 UTC, i544c-me commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = computed(defaultStore.makeGetterSetter('imageCompressionLossy'));
@anatawa12 ありがとうございます！確かにそれなら互換性維持できそうですね、明日やってみます！

2024-04-21 13:08 UTC, i544c-me commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = computed(defaultStore.makeGetterSetter('imageCompressionLossy'));
@anatawa12 修正してみました。一応 Misskey アップデート時に互換性を維持したままになることを確認しました。
ご確認のほどよろしくお願いします🙏
https://github.com/niri-la/misskey.niri.la/pull/179/commits/d3a4ccf7ad5b1d94287cc055245dc4ea8acfe860

2024-04-21 13:36 UTC, anatawa12 reviewed
ありがとうございます。デフォルト値に関する小さな修正をお願いします

2024-04-21 13:36 UTC, anatawa12 commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = ref(!!imageCompressionMode.value?.endsWith('CompressLossy'));
```suggestion
const imageResize = ref(imageCompressionMode.value?.startsWith('resize') ?? true);
const imageCompressionLossy = ref(imageCompressionMode.value?.endsWith('CompressLossy') ?? false);
```

デフォルト値をわかりやすくしたいです。
またもともとのデフォルトが`resizeCompress`なのでnullのときには`imageResize`が`true`になるようにしたいです。

2024-04-21 14:21 UTC, Sayamame-beans commented
「オリジナル画像を保持しない場合に、Web公開用画像の圧縮形式を選択できます。」の話がなくなるので、何の場合に作用する設定なのか若干分かりづらくなる可能性が少しありそうですかね…? どうやって対応しようかな

2024-04-22 00:19 UTC, anatawa12 commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = ref(!!imageCompressionMode.value?.endsWith('CompressLossy'));
こう書きましたがそもそもimageCompressionModeがnullableにしてるのなんでだ...?nullableでなくて良さそうなのでそのままで良さそうですねすみません。

2024-04-22 00:19 UTC, anatawa12 approved these changes
実装的にはOK

2024-04-22 00:24 UTC, Sayamame-beans commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = ref(!!imageCompressionMode.value?.endsWith('CompressLossy'));
独自実装であり元々存在しないデータだったからとか…? デフォルト値代入するようになってるとかなら謎ですが

2024-04-22 00:32 UTC, anatawa12 commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = ref(!!imageCompressionMode.value?.endsWith('CompressLossy'));
デフォルト値が入ってるはずで、何故か明示的にnullを許容するようになってるのですよね

2024-04-22 02:55 UTC, i544c-me commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = ref(!!imageCompressionMode.value?.endsWith('CompressLossy'));
そうなんですよね... nullable が気になってこのような実装になりました。
ではここはこのままでいきます。

2024-04-22 03:03 UTC, i544c-me commented
> 「オリジナル画像を保持しない場合に、Web公開用画像の圧縮形式を選択できます。」の話がなくなるので、何の場合に作用する設定なのか若干分かりづらくなる可能性が少しありそうですかね…? どうやって対応しようかな

そうなんですよね...「オリジナル画像を保持する」にチェックを入れた時は、圧縮形式の設定2つを見えなくしてしまうか、トグルを [disabled](https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/disabled) の状態にするかしたら、分かりやすいかなとは思いました。

2024-04-22 03:10 UTC, anatawa12 commented on packages/frontend/src/pages/settings/drive.vue
> +const imageCompressionLossy = ref(!!imageCompressionMode.value?.endsWith('CompressLossy'));
見た感じ`reactionAcceptance`からコピペしてたっぽいですね... reactionAcceptanceはnullに意味がちゃんとあるのであまり考えずにコピペしてそう...すみません

2024-04-22 03:11 UTC, anatawa12 commented
> そうなんですよね...「オリジナル画像を保持する」にチェックを入れた時は、圧縮形式の設定2つを見えなくしてしまうか、トグルを [disabled](https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/disabled) の状態にするかしたら、分かりやすいかなとは思いました。

そうすると投稿画面でアップロード時にオリジナル画像を保持するをオフにした際の設定ができなくなるのでその実装では困ると思います

2024-04-22 14:10 UTC, i544c-me commented
なるほど、そういえば投稿画面でも保持の設定ありましたね...

では設定画面に説明を加える方向が良いですかね...？こんな感じはいかがでしょう？
![image](https://github.com/niri-la/misskey.niri.la/assets/131976645/95e2bf15-112a-4b5a-99c7-724ab42f3eb2)

2024-04-22 14:51 UTC, anatawa12 approved these changes
コードはよし。あとは翻訳さやまめさんお願いします

2024-04-22 23:14 UTC, Sayamame-beans requested changes
これは原文からそうみたいなのですが、2560x2560"より小さくなるように"ではないような気がふとしました。
処理うろ覚えですが、2560x2560は大丈夫だった気がしていて…2560x2560"以下になるように"なのかな、と…
(そうだとして、本家側で表記修正してもらったタイミングで直すで良いかなぁという感じもあります)

2024-04-22 23:14 UTC, Sayamame-beans commented on locales/ja-JP.yml
> +  description: "オリジナル画像を保持しない場合に、Web公開用画像の圧縮形式を選択できます"
```suggestion
  description: "オリジナル画像を保持しない場合に、Web公開用画像の圧縮形式を選択できます。"
```

2024-04-22 23:14 UTC, Sayamame-beans commented on packages/frontend/src/scripts/upload/compress-config.ts
> +	const compressKind = defaultStore.state.imageCompressionMode.endsWith('CompressLossy') ? 'lossy' : 'lossless';
```suggestion
	const compressKind = defaultStore.state.imageCompressionMode.endsWith('CompressLossy') ? 'lossy' : inputCompressKind;
```
ですか?

2024-04-22 23:14 UTC, Sayamame-beans commented on locales/en-US.yml
> +  description: "If keep original image turn off, you can select the image compression format for web publication."
```suggestion
  description: "If 'Keep original image' turned off, you can select the image compression format for web publication."
```

2024-04-22 23:14 UTC, Sayamame-beans commented on locales/en-US.yml
> +  imageCompressionLossyDescription: "If turned off, select mode lossy or lossless compression automatically depending on the original image."
```suggestion
  imageCompressionLossyDescription: "If turned off, the compression mode is automatically selected to lossy or lossless depending on the original image."
```

2024-04-23 13:39 UTC, i544c-me commented
@Sayamame-beans ありがとうございます！修正取り込みました🙏

> 本家側で表記修正してもらったタイミングで直す

本家というのは misskey-dev/misskey ですかね？本家の方では 2560x2560 より小さくする説明自体無いような気がするのですが...
認識合っていれば、この PR で修正してしまって良いですかね...？

2024-04-23 13:41 UTC, Sayamame-beans commented
> 本家の方では 2560x2560 より小さくする説明自体無いような気がするのですが...

確かにありませんでした(ごちゃまぜになってました、すみません)
修正助かります、お願いします🙏

2024-04-23 13:58 UTC, i544c-me commented
修正しました！ご確認お願いします🙏

2024-04-23 14:20 UTC, Sayamame-beans approved these changes
見た感じ良さそうです！ありがとうございます！

2024-04-25 13:29 UTC, merged