Selectable resize scale
niwaniwa/misskey pull request #193
Opened 2024-05-25 14:34 UTC by Sayamame-beans

## What

縮小時の解像度を2048, 2560, 4096, 8192から選択可能にします。

縮小した方がファイルサイズが大きくなってしまう場合は縮小していない画像を利用する、というMisskeyの仕様があるため、この解像度設定よりも大きなままで保存されることもあります。

という旨をimageResizeDescriptionに加えるか迷っています。

## Why

fix: #182 

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-05-25 18:55 UTC, anatawa12 requested changes

2024-05-25 18:55 UTC, anatawa12 commented on locales/ja-JP.yml
> +  _imageResizeSize:
他に倣うと_imageResizeSize.titleのようにすると思う

2024-05-25 18:55 UTC, anatawa12 commented on packages/frontend/src/scripts/upload/compress-config.ts
> +	const sizeConfig = resize ? { maxWidth: parseInt(defaultStore.state.imageResizeSize, 10), maxHeight: parseInt(defaultStore.state.imageResizeSize, 10) } : noResizeSizeConfig;
行が長いし二回パースしてるの無駄に思えるので行分けたい

2024-05-26 02:58 UTC, Sayamame-beans commented
ここまでくるとWebPublicの画質もSelectableにすれば良いんじゃないかという気持ちになってきました。

2024-05-26 04:22 UTC, anatawa12 approved these changes
OKかな

2024-06-03 04:58 UTC, merged