ローカルユーザーが誰もフォローしていないリモートユーザーによるノートのブロックの改善
niwaniwa/misskey pull request #206
Opened 2024-06-29 13:02 UTC by anatawa12

## What

Fixes some portion of #146 

## Why

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-06-29 13:03 UTC, anatawa12 commented on packages/backend/src/core/NoteCreateService.ts
> +		if (meta.nirilaBlockMentionsFromUnfamiliarRemoteUsers && user.host !== null && willCauseNotification && !isAllowedToCreateNotification()) {
正直動作確認はできてない

2024-06-29 13:04 UTC, anatawa12 commented on packages/frontend/src/pages/admin/moderation.vue
> +					</MkTextarea>
どちらの設定もコンパネからいじれます

2024-06-29 13:18 UTC, anatawa12 commented
lintは後でやります

2024-06-29 13:25 UTC, anatawa12 commented on packages/backend/src/core/NoteCreateService.ts
> +		}
```suggestion
		const isAllowedToCreateNotification = () => {
			const targetUserIds: string[][] = [];
			targetUserIds.push(mentionedUsers.filter(x => x.host == null).map(x => x.id));
			if (data.visibility === 'specified' && data.visibleUsers != null)
				targetUserIds.push(data.visibleUsers.filter(x => x.host == null).map(x => x.id));
			if (data.reply != null && data.reply.userHost == null) targetUserIds.push([data.reply.userId]);
			if (this.isRenote(data) && this.isQuote(data) && data.renote.userHost === null) targetUserIds.push([data.renote.userId]);
			const allowedIds = new Set(meta.nirilaAllowedUnfamiliarRemoteUserIds);
			for (const targetUserIds1 of targetUserIds) {
				for (const targetUserId of targetUserIds1) {
					if (allowedIds.has(targetUserId)) {
						return true;
					}
				}
			}
			return false;
		};
```

2024-06-29 13:27 UTC, Sayamame-beans commented on packages/backend/src/core/NoteCreateService.ts
> +		if (meta.nirilaBlockMentionsFromUnfamiliarRemoteUsers && user.host !== null && willCauseNotification && !isAllowedToCreateNotification()) {
string[][]をforで回してるのが少し気になりました
ただ、Setに配列から直接追加は出来ない(Constructorでだけ変換化)っぽいので、代わりのアイデアとして…
- targetUserIdsをstring[]に
- pushの代わりにconcat
- forの直前でtargetUserIdsをSetに変換

とかで良い感じになったりしませんかね

2024-06-29 13:29 UTC, anatawa12 commented on packages/backend/src/core/NoteCreateService.ts
> +				targetUserIds.push(data.visibleUsers.filter(x => x.host == null).map(x => x.id));
```suggestion
			if (data.visibility === 'specified' && data.visibleUsers != null) targetUserIds.push(data.visibleUsers.filter(x => x.host == null).map(x => x.id));
```

2024-06-29 13:38 UTC, Sayamame-beans commented on packages/backend/src/core/NoteCreateService.ts
> +		if (meta.nirilaBlockMentionsFromUnfamiliarRemoteUsers && user.host !== null && willCauseNotification && !isAllowedToCreateNotification()) {
concatじゃなくて良いかも
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/push#%EF%BC%92%E3%81%A4%E3%81%AE%E9%85%8D%E5%88%97%E3%82%92%E3%83%9E%E3%83%BC%E3%82%B8%E3%81%99%E3%82%8B

2024-06-29 13:42 UTC, anatawa12 commented on packages/frontend/src/pages/admin/moderation.vue
> +		nirilaAllowedUnfamiliarRemoteUserIds: nirilaAllowedUnfamiliarRemoteUserIds.value == ''
```suggestion
		nirilaAllowedUnfamiliarRemoteUserIds: nirilaAllowedUnfamiliarRemoteUserIds.value === ''
```

2024-06-29 14:03 UTC, anatawa12 commented on packages/backend/src/core/NoteCreateService.ts
> +		if (meta.nirilaBlockMentionsFromUnfamiliarRemoteUsers && user.host !== null && willCauseNotification && !isAllowedToCreateNotification()) {
場フォーマンスを地味に気にしてこうしたけど無駄かもしれない。

2024-06-30 05:29 UTC, Sayamame-beans requested changes
流れてきたノートの通知対象ユーザーの中に、1人でも通知を許可するユーザーが居たら、そのノートは(対象者全員に)通知されるって感じであってます?
雰囲気的には大体良さそうですかね～

2024-06-30 05:29 UTC, Sayamame-beans commented on CHANGELOG.md
> +- 未知のリモートユーザからの通知を生成するノートをブロックする機能の改善 (#206)
```suggestion
- 未知のリモートユーザーによる通知が発生するノートをブロックする機能の改善 (#206)
```

2024-06-30 05:29 UTC, Sayamame-beans commented on packages/frontend/src/pages/admin/moderation.vue
> +						<template #label>未知のリモートユーザからの通知を生成するノートをブロックする</template>
```suggestion
						<template #label>未知のリモートユーザーによる通知が発生するノートをブロックする</template>
```

2024-06-30 05:29 UTC, Sayamame-beans commented on packages/frontend/src/pages/admin/moderation.vue
> +						<template #label>未知のリモートユーザからの通知を許可するローカルユーザのid</template>
```suggestion
						<template #label>未知のリモートユーザーによる通知を許可するローカルユーザーのID</template>
```

2024-06-30 05:29 UTC, Sayamame-beans commented on packages/frontend/src/pages/admin/moderation.vue
> +						<template #caption>9grmcrkrslのようなユーザのidであって@adminのようなユーザ名ではないことに気をつけてください。</template>
```suggestion
						<template #caption>`@admin`のようなユーザ名ではなく、`9grmcrkrsl`のようなユーザーのIDであることに注意してください。</template>
```

2024-06-30 07:05 UTC, anatawa12 commented
> 流れてきたノートの通知対象ユーザーの中に、1人でも通知を許可するユーザーが居たら、そのノートは(対象者全員に)通知されるって感じであってます?

No 全員が許可されてないとだめです。(じゃないとスパムの抜け道になるので)

2024-06-30 07:26 UTC, Sayamame-beans commented
> > 流れてきたノートの通知対象ユーザーの中に、1人でも通知を許可するユーザーが居たら、そのノートは(対象者全員に)通知されるって感じであってます?
> 
> No 全員が許可されてないとだめです。(じゃないとスパムの抜け道になるので)

early returnしててそういうロジックになってないような気が…?

2024-06-30 07:41 UTC, anatawa12 commented
入ってないときにreturn faldeしたつもりになってた

2024-06-30 08:17 UTC, anatawa12 commented on packages/backend/src/core/NoteCreateService.ts
> +		if (meta.nirilaBlockMentionsFromUnfamiliarRemoteUsers && user.host !== null && willCauseNotification && !isAllowedToCreateNotification()) {
平らにした

2024-06-30 09:32 UTC, Sayamame-beans commented on packages/backend/src/core/NoteCreateService.ts
> +				...mentionedUsers.filter(x => x.host == null).map(x => x.id),
mentionedUsersはnot nullable?

2024-06-30 09:32 UTC, Sayamame-beans commented
他はなんとなく良さそう

2024-06-30 09:33 UTC, anatawa12 commented on packages/backend/src/core/NoteCreateService.ts
> +				...mentionedUsers.filter(x => x.host == null).map(x => x.id),
??=[]してるのではい

2024-06-30 09:34 UTC, Sayamame-beans approved these changes
ok

2024-06-30 09:35 UTC, merged