fix(backend): original image is not original image on web page
niwaniwa/misskey pull request #59
Opened 2023-09-18 11:02 UTC by anatawa12

## What

## Why

https://github.com/misskey-dev/misskey/pull/11760#issuecomment-1713667987

misskey-dev#11844

絶対にユーザの意図した動作ではないので再圧縮条件からサイズとEXIFを消す

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-09-18 11:17 UTC, anatawa12 commented on packages/backend/src/core/DriveService.ts
> +			//!(metadata.exif ?? metadata.iptc ?? metadata.xmp ?? metadata.tifftagPhotoshop) &&
```suggestion
				type !== 'image/avif' && // not supported by Mastodon and MS Edge
			!(metadata.exif ?? metadata.iptc ?? metadata.xmp ?? metadata.tifftagPhotoshop)
```

2023-09-18 11:38 UTC, anatawa12 commented
@Sayamame-beans とりあえず8Kまでサイズがそのままになるようにした

2023-09-19 07:31 UTC, Sayamame-beans commented
webpublicの上限を8Kにすると、別のサーバーにも8Kのまま渡っていきそうな気が少しします(そして恐らく、キャッシュするようになっていればそのサーバー上で別途保存されることになる)
連合で流れてきた画像を2Kにする処理がデフォルトで入っているなら良いのですが、そうでないなら、相手方のサーバーの容量を圧迫してしまう可能性が…?

2023-09-19 08:10 UTC, anatawa12 commented
その問題はそもそもMisskey側の問題なきがするし、リモートで8Kで見えるのがユーザの意図した動作だと思ってるんだけども違うのか

2023-09-19 08:30 UTC, Sayamame-beans commented
いや、まあ…リモートからでも8Kで見えるのが理想ではあります。
ただ、 #60 で言及しているように、デフォルトが常に8Kまで膨れると困るという意見もあります。(とはいえ、webpublic用にwebp/pngとして可逆再圧縮は掛かっているのでしょうし、実際にどのくらい通信量/描画負荷に差が出るかというところではありますが)

2023-09-19 08:31 UTC, Sayamame-beans commented
正直に言うと、今の私はどういう形に収まるのがベストなのか掴めずに居るので、言っていることが迷走しているかもしれません…

2023-09-19 11:15 UTC, anatawa12 commented
正直なところ通信量をそこまで圧縮すべきものだと思ってないのですよね...

2023-09-19 11:37 UTC, Sayamame-beans commented
> 通信量

主に、上限があったり従量課金だったりするモバイル環境、あるいは低速な回線環境等ではツラいんじゃないかなとは思いますね
描画負荷はモバイル系で顕著かも?

2023-09-19 22:33 UTC, niwaniwa commented
8kでもいい気はする...!
issueでも書きましたがconfigで設定できると嬉しいかも...?

2023-09-20 18:04 UTC, anatawa12 commented
とりあえず起動時configにします

2023-09-21 07:29 UTC, Sayamame-beans commented
個人的には、バランスを考えると4Kがちょうどいいのかなと思い始めてきました。(元々が2Kしか無かったわけですし…)
他にも色々考えましたが、WQHDは2Kからの上がり幅としては少なく、8Kだと16倍でちょっと大きすぎるかな?という感じで、中間と考えると3Kかな?とも思いましたが、3Kは中途半端な値なので、そうするぐらいなら4Kで良いかな～と

2023-09-21 07:37 UTC, anatawa12 commented
とりあえずconfigにしました

2023-09-24 11:09 UTC, Sayamame-beans commented
> 絶対にユーザの意図した動作ではないので再圧縮条件からサイズとEXIFを消す

消えていないような…?

2023-09-24 13:05 UTC, Sayamame-beans requested changes

2023-09-24 13:05 UTC, Sayamame-beans commented on CHANGELOG.md
> +- 4K/8K画像が2K以下になってしまうのを修正しました
```suggestion
- 4K/8K画像が2K以下で表示されてしまう問題を修正しました
  - 既存のファイルは更新されず、新規アップロード分にのみ適用されます
```

2023-09-24 13:05 UTC, Sayamame-beans commented on packages/backend/src/core/DriveService.ts
>  			!(metadata.exif ?? metadata.iptc ?? metadata.xmp ?? metadata.tifftagPhotoshop) &&
https://github.com/niri-la/misskey.niri.la/pull/59#issuecomment-1732546726 コメント該当箇所

2023-09-24 13:07 UTC, Sayamame-beans commented on packages/backend/src/core/DriveService.ts
>  			!(metadata.exif ?? metadata.iptc ?? metadata.xmp ?? metadata.tifftagPhotoshop) &&
EXIFをどうするかの話があるから後回しの方が良いのか、と今思い直しました
#61

2023-09-24 13:08 UTC, anatawa12 commented on packages/backend/src/core/DriveService.ts
>  			!(metadata.exif ?? metadata.iptc ?? metadata.xmp ?? metadata.tifftagPhotoshop) &&
意図的に一旦戻したのでdescriptionのほうが正しくない

2023-09-26 01:08 UTC, merged