feat(frontend): 8桁RRGGBBAAのサポート
niwaniwa/misskey pull request #87
Opened 2023-11-25 19:20 UTC by KisaragiEffective

## What

close #86

## Why

issue通りの内容のため省略

## Additional info (optional)
* 5桁の色入力を受け付けなくなりますが現行バージョンでは色がつかないため実質breaking changeではありません

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-11-25 19:54 UTC, Sayamame-beans commented
`/^[0-9a-f]{3,4}([0-9a-f]{2}|[0-9a-f]{4})?$/`だと、3文字から8文字までの全てのパターンに一致しませんか?
3: 3+0
4: 4+0
5: 3+2
6: 4+2
7: 3+4
8: 4+4

2023-11-26 04:23 UTC, anatawa12 commented
upstreamに投げて欲しさある。連合結果があんま良くなくなると思うし

2023-11-27 07:09 UTC, Sayamame-beans commented
> `/^[0-9a-f]{3,4}([0-9a-f]{2}|[0-9a-f]{4})?$/`だと、3文字から8文字までの全てのパターンに一致しませんか? 3: 3+0 4: 4+0 5: 3+2 6: 4+2 7: 3+4 8: 4+4

とりあえず…これはこのままで大丈夫なのでしょうか? (3文字から8文字までの全てのパターンで一致することを確認済みです)

2023-11-28 11:05 UTC, Sayamame-beans requested changes
issueやPRでの説明内容とコード内容が一致しておらず、確認が行われるまでこのPRを承認することが出来ません。
(また、連合の観点から本家リポジトリにPRすることを推奨します)

2023-11-28 17:06 UTC, KisaragiEffective commented
レビューしていただきありがとうございます。修正済みのコミットを misskey-dev#12496 として提出したのでcloseします。

2023-11-28 17:06 UTC, closed without merging